import java.sql.*;
import javax.swing.*;
import java.awt.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewStock.java
 *
 * Created on 1 Jul, 2018, 12:08:22 AM
 */

/**
 *
 * @author Abhinav
 */
public class UpdateStock extends javax.swing.JFrame {


    /** Creates new form NewStock */
    public UpdateStock() {
        
        
        ImageIcon i = new ImageIcon("newstock.png");
        JLabel l = new JLabel(i);
        //new NewStock().getContentPane().setBackground(Color.BLACK);
        setContentPane(l);
        initComponents();
        getids();
    }
    private void getids()
    {
        try
        {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con = DriverManager.getConnection("jdbc:odbc:atmobilestoredsn");
        Statement stmt = con.createStatement();
        String query = "select ProductID from tblstockdetails";
        ResultSet rs = stmt.executeQuery(query);
        while(rs.next())
        {
            cbid.addItem(rs.getString("ProductID"));
        }

        con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblid = new javax.swing.JLabel();
        lblbrand = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblram = new javax.swing.JLabel();
        lblrom = new javax.swing.JLabel();
        lblslot = new javax.swing.JLabel();
        lblrearcam = new javax.swing.JLabel();
        lblrear = new javax.swing.JLabel();
        lblbattery = new javax.swing.JLabel();
        lblandver = new javax.swing.JLabel();
        lblratio = new javax.swing.JLabel();
        lblglass = new javax.swing.JLabel();
        lblscreen = new javax.swing.JLabel();
        lblport = new javax.swing.JLabel();
        lblcharge = new javax.swing.JLabel();
        lblprocessor = new javax.swing.JLabel();
        lblnetwork = new javax.swing.JLabel();
        txtandver = new javax.swing.JTextField();
        txtbrand = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtram = new javax.swing.JTextField();
        txtslot = new javax.swing.JTextField();
        txtrom = new javax.swing.JTextField();
        txtfrontcam = new javax.swing.JTextField();
        txtrearcam = new javax.swing.JTextField();
        txtbattery = new javax.swing.JTextField();
        txtratio = new javax.swing.JTextField();
        txtglass = new javax.swing.JTextField();
        txtscreen = new javax.swing.JTextField();
        txtcharge = new javax.swing.JTextField();
        txtport = new javax.swing.JTextField();
        txtprocessor = new javax.swing.JTextField();
        lblprice = new javax.swing.JLabel();
        lblwireless = new javax.swing.JLabel();
        txtnetwork = new javax.swing.JTextField();
        txtwireless = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        lblqty = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbid = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblid.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblid.setForeground(new java.awt.Color(255, 0, 0));
        lblid.setText("ProductID");

        lblbrand.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblbrand.setForeground(new java.awt.Color(255, 0, 0));
        lblbrand.setText("Brand");

        lblname.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblname.setForeground(new java.awt.Color(255, 0, 0));
        lblname.setText("Model");

        lblram.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblram.setForeground(new java.awt.Color(255, 0, 0));
        lblram.setText("RAM");

        lblrom.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblrom.setForeground(new java.awt.Color(255, 0, 0));
        lblrom.setText("ROM");

        lblslot.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblslot.setForeground(new java.awt.Color(255, 0, 0));
        lblslot.setText("Memory Slot");

        lblrearcam.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblrearcam.setForeground(new java.awt.Color(255, 0, 0));
        lblrearcam.setText("Rear Camera");

        lblrear.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblrear.setForeground(new java.awt.Color(255, 0, 0));
        lblrear.setText("Front Camera");

        lblbattery.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblbattery.setForeground(new java.awt.Color(255, 0, 0));
        lblbattery.setText("Battery");

        lblandver.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblandver.setForeground(new java.awt.Color(255, 0, 0));
        lblandver.setText("Android Version");

        lblratio.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblratio.setForeground(new java.awt.Color(255, 0, 0));
        lblratio.setText("Screen to Body Ratio");

        lblglass.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblglass.setForeground(new java.awt.Color(255, 0, 0));
        lblglass.setText("Glass Protection");

        lblscreen.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblscreen.setForeground(new java.awt.Color(255, 0, 0));
        lblscreen.setText("Screen Resolution");

        lblport.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblport.setForeground(new java.awt.Color(255, 0, 0));
        lblport.setText("Charging Port");

        lblcharge.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblcharge.setForeground(new java.awt.Color(255, 0, 0));
        lblcharge.setText("Quick Charge");

        lblprocessor.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblprocessor.setForeground(new java.awt.Color(255, 0, 0));
        lblprocessor.setText("Processor");

        lblnetwork.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblnetwork.setForeground(new java.awt.Color(255, 0, 0));
        lblnetwork.setText("Network Supported");

        txtbrand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbrandFocusLost(evt);
            }
        });

        txtbattery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbatteryActionPerformed(evt);
            }
        });

        lblprice.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblprice.setForeground(new java.awt.Color(255, 0, 0));
        lblprice.setText("Price");

        lblwireless.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblwireless.setForeground(new java.awt.Color(255, 0, 0));
        lblwireless.setText("Wireless Charging");

        lblqty.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblqty.setForeground(new java.awt.Color(255, 0, 0));
        lblqty.setText("Quantity");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AT Update Mobile Stock Screen");

        cbid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbidFocusLost(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblbrand)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblid)
                                    .addComponent(lblname)
                                    .addComponent(lblram)
                                    .addComponent(lblrom)
                                    .addComponent(lblslot))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbid, 0, 103, Short.MAX_VALUE)
                                    .addComponent(txtram, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(txtbrand, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(txtrom, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(txtslot, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(txtfrontcam, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(txtrearcam, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(txtbattery, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                                .addGap(93, 93, 93))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblrearcam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblbattery)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblrear)
                        .addGap(243, 243, 243)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblscreen)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblandver)
                                    .addComponent(lblratio)
                                    .addComponent(lblglass)
                                    .addComponent(lblnetwork)
                                    .addComponent(lblwireless)
                                    .addComponent(lblcharge))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtwireless, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtcharge, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtscreen, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtglass, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtratio, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtport, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtprocessor, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtnetwork, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtandver, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblprocessor)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblport)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(lblprice)
                        .addGap(26, 26, 26)
                        .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton2)
                        .addGap(113, 113, 113)
                        .addComponent(jButton3)
                        .addContainerGap(142, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblqty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblandver)
                    .addComponent(txtandver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblid)
                    .addComponent(cbid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbrand)
                    .addComponent(lblratio)
                    .addComponent(txtbrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtratio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblname)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblglass)
                        .addComponent(txtglass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblram)
                            .addComponent(lblscreen))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblrom, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblport)
                            .addComponent(txtport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtscreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblslot)
                                .addComponent(lblcharge))
                            .addComponent(txtslot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblrear)
                                .addComponent(txtfrontcam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblprocessor)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtprocessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblrearcam)
                    .addComponent(txtrearcam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnetwork)
                    .addComponent(txtnetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbattery)
                    .addComponent(txtbattery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblwireless)
                    .addComponent(txtwireless, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprice)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblqty)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbatteryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbatteryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbatteryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
{
  Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
  Connection con = DriverManager.getConnection("jdbc:odbc:atmobilestoredsn");
  Statement stmt= con.createStatement();
  String query = "Update tblstockdetails set Brand = '"+txtbrand.getText()+"', PName='"+txtname.getText()+"', RAM = '"+txtram.getText()
          +"',ROM = '"+txtrom.getText()+"', MemorySlot = '"+txtslot.getText()+"', FrontCamera = '"+txtfrontcam.getText()
          +"',RearCamera = '"+txtrearcam.getText()+"', Battery = '"+txtbattery.getText()+"', AndroidVersion = '"+txtandver.getText()
          +"', ScreentoBody = '"+txtratio.getText()+"', GlassProtection = '"+txtglass.getText()+"', ScreenResolution = '"+txtscreen.getText()
          +"', ChargingPort = '"+txtport.getText()+"', QuickCharge = '"+txtcharge.getText()+"', Processor = '"+txtprocessor.getText()
          +"', Network = '"+txtnetwork.getText()+"',WirelessCharging = "+txtwireless.getText()+", Price = "+Integer.parseInt(txtprice.getText())
          +", Quantity = "+Integer.parseInt(txtqty.getText())+" where ProductID = '"+cbid.getSelectedItem().toString()+"'";
  int x = stmt.executeUpdate(query);
  JOptionPane.showMessageDialog(null, "Stock updated successfully ");
  con.close();
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null, e);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbrandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbrandFocusLost

// TODO add your handling code here:
    }//GEN-LAST:event_txtbrandFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

txtbrand.setText("");
txtname.setText("");
txtram.setText("");
txtrom.setText("");
txtslot.setText("");
txtfrontcam.setText("");
txtrearcam.setText("");
txtbattery.setText("");
txtandver.setText("");
txtratio.setText("");
txtglass.setText("");
txtscreen.setText("");
txtport.setText("");
txtcharge.setText("");
txtprocessor.setText("");
txtnetwork.setText("");
txtwireless.setText("");
txtprice.setText("");
txtqty.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbidFocusLost
try
{
  Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
  Connection con = DriverManager.getConnection("jdbc:odbc:atmobilestoredsn");
  Statement stmt= con.createStatement();
  String query = "select * from tblstockdetails where ProductID = '"+cbid.getSelectedItem().toString()+"'";
  ResultSet rs = stmt.executeQuery(query);
  if(rs.next())
  {
      txtbrand.setText(rs.getString("Brand"));
      txtname.setText(rs.getString("PName"));
      txtram.setText(rs.getString("RAM"));
      txtrom.setText(rs.getString("ROM"));
      txtslot.setText(rs.getString("MemorySlot"));
      txtfrontcam.setText(rs.getString("FrontCamera"));
      txtrearcam.setText(rs.getString("RearCamera"));
      txtbattery.setText(rs.getString("Battery"));
      txtandver.setText(rs.getString("AndroidVersion"));
      txtratio.setText(rs.getString("ScreentoBody"));
      txtglass.setText(rs.getString("GlassProtection"));
      txtscreen.setText(rs.getString("ScreenResolution"));
      txtport.setText(rs.getString("ChargingPort"));
      txtcharge.setText(rs.getString("QuickCharge"));
      txtprocessor.setText(rs.getString("Processor"));
      txtnetwork.setText(rs.getString("Network"));
      if(rs.getString("WirelessCharging").equals("1"))
      {
          txtwireless.setText("Yes");
      }
      else
      txtwireless.setText("No");
      txtprice.setText(""+rs.getInt("Price"));
      txtqty.setText(""+rs.getInt("Quantity"));
  }
  con.close();
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null, e);
}// TODO add your handling code here:
    }//GEN-LAST:event_cbidFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 try
 {
  Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
  Connection con = DriverManager.getConnection("jdbc:odbc:atmobilestoredsn");
  Statement stmt= con.createStatement();
  String query = "delete from tblstockdetails where ProductID = '"+cbid.getSelectedItem().toString()+"'";
  int x = stmt.executeUpdate(query);
  JOptionPane.showMessageDialog(null, "Stock Successfully Deleted");
  con.close();
 }
 catch(Exception e)
 {
  JOptionPane.showMessageDialog(null, e);
 }
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateStock n = new UpdateStock();
                n.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblandver;
    public javax.swing.JLabel lblbattery;
    public javax.swing.JLabel lblbrand;
    public javax.swing.JLabel lblcharge;
    public javax.swing.JLabel lblglass;
    public javax.swing.JLabel lblid;
    public javax.swing.JLabel lblname;
    public javax.swing.JLabel lblnetwork;
    public javax.swing.JLabel lblport;
    private javax.swing.JLabel lblprice;
    public javax.swing.JLabel lblprocessor;
    private javax.swing.JLabel lblqty;
    public javax.swing.JLabel lblram;
    public javax.swing.JLabel lblratio;
    public javax.swing.JLabel lblrear;
    public javax.swing.JLabel lblrearcam;
    public javax.swing.JLabel lblrom;
    public javax.swing.JLabel lblscreen;
    public javax.swing.JLabel lblslot;
    public javax.swing.JLabel lblwireless;
    public javax.swing.JTextField txtandver;
    public javax.swing.JTextField txtbattery;
    public javax.swing.JTextField txtbrand;
    public javax.swing.JTextField txtcharge;
    public javax.swing.JTextField txtfrontcam;
    public javax.swing.JTextField txtglass;
    public javax.swing.JTextField txtname;
    public javax.swing.JTextField txtnetwork;
    public javax.swing.JTextField txtport;
    public javax.swing.JTextField txtprice;
    public javax.swing.JTextField txtprocessor;
    public javax.swing.JTextField txtqty;
    public javax.swing.JTextField txtram;
    public javax.swing.JTextField txtratio;
    public javax.swing.JTextField txtrearcam;
    public javax.swing.JTextField txtrom;
    public javax.swing.JTextField txtscreen;
    public javax.swing.JTextField txtslot;
    public javax.swing.JTextField txtwireless;
    // End of variables declaration//GEN-END:variables

}
